### PR TITLE
Instance init - workaround group participants to db sync after instance init

### PR DESCRIPTION
**Pull request by luispimenta**
workaround group participants to db sync

### CODE REVIEW

**Comment by salman0ansari** [comment]
Does his fix #237 ?

**Comment by salman0ansari** [comment]
again your pr contains old commits

**Comment by salman0ansari** [comment]
I think to fix this 
you have to make commit in main branch and open pr from main branch🤔

**Comment by luispimenta** [comment]
@salman0ansari yes, I solved it but it wouldn't be the best way, but it worked!

exact, I do just that by exiting main, a new brach:

git checkout -b new-name

and every time it goes with the commits, what am I doing wrong?

**Comment by salman0ansari** [comment]
> @salman0ansari yes, I solved it but it wouldn't be the best way, but it worked!
> 
> exact, I do just that by exiting main, a new brach:
> 
> git checkout -b new-name
> 
> and every time it goes with the commits, what am I doing wrong?

You dont have to create a new branch everytime you make some changes you can make change in main branch and commit it. It will work just fine

**Pull request merged**
