### PR TITLE
Update Postman to avoid error on  message/mediaurl

### PR DESCRIPTION
**Pull request by johbs**
Update Postman to avoid error on  message/mediaurl : TypeError: Cannot use 'in' operator to search for ... Cannot read properties of undefined (reading 'includes')

### CODE REVIEW

**Comment by salman0ansari** [comment]
does removing a `}` fixes this?

**Comment by johbs** [comment]
> does removing a `}` fixes this?

No. We need to change the body type from _form-data_ to _x-www-form-urlencoded_ to use a function _/message/mediaurl_. Otherwise it doesnt work.

**Comment by salman0ansari** [comment]
> > does removing a `}` fixes this?
> 
> No. We need to change the body type from _form-data_ to _x-www-form-urlencoded_ to use a function _/message/mediaurl_. Otherwise it doesnt work.

Why did you open this PR? 😂

**Comment by salman0ansari** [comment]
fixed [6c4552b](https://github.com/salman0ansari/whatsapp-api-nodejs/commit/6c4552baf0184316bc8a736fc8651563c6554fac)

**Pull request closed without merging**
