### PR TITLE
update database groups if owner left

### PR DESCRIPTION
**Pull request by luispimenta**
if group owner left, update and remove from database

@salman0ansari thanks about commits works now!

### CODE REVIEW

**Comment by salman0ansari** [comment]
did you use prettier before committing?

**Comment by luispimenta** [comment]
> 

no, in my main I pushed --force with your main, then it was 100% synchronized, there in the master or creating a branch when they are 100% synchronized, PR only goes to my new commits

**Comment by salman0ansari** [comment]
> 

pls run `yarn format:write` then commit changes

**Comment by salman0ansari** [comment]
or you can use husky i already setup a pre-commit hook
`yarn configure-husky`

**Comment by luispimenta** [comment]
done!

**Pull request merged**
