### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dasmond1**
Add Postman Documentation related to my issue #39

### CODE REVIEW

**Comment by salman0ansari** [comment]
in docs what do you mean by
`Repack and Rebuild`

**Comment by dasmond1** [comment]
> in docs what do you mean by `Repack and Rebuild`

i dont't have any idea what should i write. LOL
do you have any idea ?
i will update soon

**Comment by salman0ansari** [comment]
`Developer - @salman0ansari   `
`Documentation - You `
simple

**Comment by dasmond1** [comment]
Updated. Check this out
https://documenter.getpostman.com/view/6033139/UVsPPjSH

**Comment by salman0ansari** [comment]
> Updated. Check this out https://documenter.getpostman.com/view/6033139/UVsPPjSH

can you send this document to my telegram?? @salman0ansari

**Comment by dasmond1** [comment]
> Owner

Sure, give me a sec

**Pull request closed without merging**
