### PR TITLE
Update instance.controller.js

### PR DESCRIPTION
**Pull request by fabriciokerber**
Created new route to accept reatore one instance and params like to init

### CODE REVIEW

**Comment by dv336699** [comment]
@fabriciokerber maybe we should pass a query parameter instead to `/restore` ?
If set, restore one, if not set, restore all.

```
localhost:333/instance/restore?key=123
```

**Comment by salman0ansari** [comment]
> @fabriciokerber maybe we should pass a query parameter instead to `/restore` ? If set, restore one, if not set, restore all.
> 
> ```
> localhost:333/instance/restore?key=123
> ```

i agree with @dv336699

**Review by salman0ansari — CHANGES_REQUESTED** [review]
add [key] query parameter in /restore endpoint
`If query restore one ..
else restore all`

**Comment by fabriciokerber** [comment]
so nice!!!

Em qui., 9 de jun. de 2022 às 08:36, Mohd Salman ***@***.***>
escreveu:

**Pull request closed without merging**
